management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 50301
spring:
  application:
    name: dispatcher-service
  devtools:
    livereload:
      port: 51301
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

logging:
  level:
    dev.ubaid: TRACE
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"