apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: ghcr.io/ubaid4j/dispatcher-service:0.0.2-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50301
          env:
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "56720"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
