apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /management/prometheus
        prometheus.io/port: "50301"
    spec:
      containers:
        - name: dispatcher-service
          image: ghcr.io/ubaid4j/dispatcher-service:0.0.2-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50301
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 50301
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 50301
            initialDelaySeconds: 5
            periodSeconds: 15
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          volumeMounts:
            - mountPath: /workspace/config
              name: dispatcher-service-volume
      volumes:
        - name: dispatcher-service-volume
          configMap:
            name: dispatcher-config